export interface PlayerWithClue {
  name: string;
  clue: string;
}

export interface CategoryData {
  id: string;
  name: string;
  players: PlayerWithClue[];
}

// Datos del juego organizados por categorías
export const gameData: Record<string, CategoryData> = {
  futbol: {
    id: 'futbol',
    name: 'Fútbol',
    players: [
      { name: 'Sergio Ramos', clue: 'Fuerte' },
      { name: 'Andrés Iniesta', clue: 'Silencioso' },
      { name: 'Gerard Piqué', clue: 'Famoso' },
      { name: 'David Villa', clue: 'Rápido' },
      { name: 'Iker Casillas', clue: 'Seguro' },
      { name: 'Fernando Torres', clue: 'Popular' },
      { name: 'Xavi Hernández', clue: 'Calmado' },
      { name: 'Cristiano Ronaldo', clue: 'Ambicioso' },
      { name: 'Lionel Messi', clue: 'Talentoso' },
      { name: 'Zinedine Zidane', clue: 'Elegante' },
      { name: 'Luka Modric', clue: 'Constante' },
      { name: 'Toni Kroos', clue: 'Preciso' },
      { name: 'Karim Benzema', clue: 'Eficaz' },
      { name: 'Robert Lewandowski', clue: 'Frío' },
      { name: 'Erling Haaland', clue: 'Potente' },
      { name: 'Kylian Mbappé', clue: 'Explosivo' },
      { name: 'Antoine Griezmann', clue: 'Creativo' },
      { name: 'Kevin De Bruyne', clue: 'Inteligente' },
      { name: 'Paul Pogba', clue: 'Irregular' },
      { name: 'Gareth Bale', clue: 'Velocidad' },
      { name: 'Eden Hazard', clue: 'Técnica' },
      { name: 'Marco Reus', clue: 'Leal' },
      { name: 'Thomas Müller', clue: 'Curioso' },
      { name: 'Harry Kane', clue: 'Serio' },
      { name: 'Raheem Sterling', clue: 'Ligero' },
      { name: 'Virgil van Dijk', clue: 'Sólido' },
      { name: 'Sadio Mané', clue: 'Intenso' },
      { name: 'Mohamed Salah', clue: 'Determinado' },
      { name: 'Bruno Fernandes', clue: 'Activo' },
      { name: 'Marcus Rashford', clue: 'Joven' },
      { name: 'Sergio Busquets', clue: 'Ordenado' },
      { name: 'Jordi Alba', clue: 'Constante' },
      { name: 'Gerard Moreno', clue: 'Discreto' },
      { name: 'Álvaro Morata', clue: 'Variable' },
      { name: 'Pedri González', clue: 'Prometedor' },
      { name: 'Gavi', clue: 'Energía' },
      { name: 'Rodri Hernández', clue: 'Estable' },
      { name: 'Aymeric Laporte', clue: 'Traidor' },
      { name: 'Thibaut Courtois', clue: 'Gigante' },
      { name: 'Jan Oblak', clue: 'Calma' },
      { name: 'Marc-André ter Stegen', clue: 'Preciso' },
      { name: 'Manuel Neuer', clue: 'Innovador' },
      { name: 'Phil Foden', clue: 'Ágil' },
      { name: 'Jack Grealish', clue: 'Estilo' },
      { name: 'Declan Rice', clue: 'Firme' },
      { name: 'Federico Valverde', clue: 'Completo' },
      { name: 'Lautaro Martínez', clue: 'Instinto' },
      { name: 'Paulo Dybala', clue: 'Hábil' },
      { name: 'Olivier Giroud', clue: 'Experiencia' },
      { name: "N'Golo Kanté", clue: 'Humilde' },
      { name: 'Joshua Kimmich', clue: 'Disciplinado' },
      { name: 'David Silva', clue: 'Tranquilo' },
      { name: 'Cesc Fàbregas', clue: 'Preciso' },
      { name: 'Isco Alarcón', clue: 'Técnico' },
      { name: 'Santi Cazorla', clue: 'Alegre' },
      { name: 'Nacho Fernández', clue: 'Discreto' },
      { name: 'Dani Carvajal', clue: 'Firme' },
      { name: 'Sergio Reguilón', clue: 'Dinámico' },
      { name: 'Koke Resurrección', clue: 'Constante' },
      { name: 'Saúl Ñíguez', clue: 'Inquieto' },
      { name: 'Ángel Di María', clue: 'Creativo' },
      { name: 'Gonzalo Higuaín', clue: 'Decidido' },
      { name: 'Jesús Navas', clue: 'Rápido' },
      { name: 'Pepe Reina', clue: 'Experto' },
      { name: 'Javi Martínez', clue: 'Seguro' },
      { name: 'César Azpilicueta', clue: 'Serio' },
      { name: 'Nacho Monreal', clue: 'Correcto' },
      { name: 'Juan Mata', clue: 'Elegante' },
      { name: 'Adama Traoré', clue: 'Físico' },
      { name: 'Thiago Alcántara', clue: 'Fluido' },
      { name: 'Rodrigo Moreno', clue: 'Equilibrado' },
      { name: 'Pau Torres', clue: 'Sereno' },
      { name: 'Dani Parejo', clue: 'Ordenado' },
      { name: 'Carlos Bacca', clue: 'Potente' },
      { name: 'João Félix', clue: 'Imprevisible' },
      { name: 'Riyad Mahrez', clue: 'Refinado' },
      { name: 'Ilkay Gündogan', clue: 'Inteligente' },
      { name: 'Bernardo Silva', clue: 'Sutil' },
      { name: 'Ruben Dias', clue: 'Serio' },
      { name: 'João Cancelo', clue: 'Activo' },
      { name: 'Achraf Hakimi', clue: 'Rápido' },
      { name: 'Presnel Kimpembe', clue: 'Decidido' },
      { name: 'Marquinhos', clue: 'Responsable' },
      { name: 'Theo Hernández', clue: 'Ofensivo' },
      { name: 'Mike Maignan', clue: 'Seguro' },
      { name: 'Franck Kessié', clue: 'Fuerte' },
      { name: 'Nicolo Barella', clue: 'Dinámico' },
      { name: 'Federico Chiesa', clue: 'Valiente' },
      { name: 'Ciro Immobile', clue: 'Constante' },
      { name: 'Rafael Leão', clue: 'Explosivo' },
      { name: 'Kai Havertz', clue: 'Suave' },
      { name: 'Jamal Musiala', clue: 'Joven' },
      { name: 'Leon Goretzka', clue: 'Fuerte' },
      { name: 'Kingsley Coman', clue: 'Ágil' },
      { name: 'Benjamin Pavard', clue: 'Formal' },
      { name: 'Alphonso Davies', clue: 'Rápido' },
      { name: 'Paolo Maldini', clue: 'Firme' },
      { name: 'Carles Puyol', clue: 'Valiente' },
      { name: 'Ronaldinho', clue: 'Magia' },
      { name: 'Ronaldo Nazário', clue: 'Explosivo' },
      { name: 'Luis Figo', clue: 'Equilibrado' },
      { name: "Samuel Eto'o", clue: 'Competitivo' },
      { name: 'Neymar Jr', clue: 'Creativo' },
      { name: 'Deco', clue: 'Técnico' },
      { name: 'Víctor Valdés', clue: 'Serio' },
      { name: 'Dani Alves', clue: 'Divertido' },
      { name: 'Roberto Carlos', clue: 'Potente' },
      { name: 'Raúl González', clue: 'Serio' },
      { name: 'Fernando Hierro', clue: 'Autoridad' },
      { name: 'Pepe', clue: 'Intenso' },
      { name: 'Álvaro Arbeloa', clue: 'Correcto' },
      { name: 'Iago Aspas', clue: 'Persistente' },
      { name: 'Joaquín Sánchez', clue: 'Divertido' },
      { name: 'Luis Enrique', clue: 'Intenso' },
      { name: 'Rivaldo', clue: 'Técnico' },
      { name: 'Xabi Alonso', clue: 'Tranquilo' },
      { name: 'Vinícius Jr', clue: 'Rápido' },
      { name: 'Rodrygo Goes', clue: 'Dinámico' },
      { name: 'Aurélien Tchouaméni', clue: 'Fuerte' },
      { name: 'Eduardo Camavinga', clue: 'Versátil' },
      { name: 'Éder Militão', clue: 'Seguro' },
      { name: 'Antonio Rüdiger', clue: 'Intenso' },
      { name: 'Brahim Díaz', clue: 'Creativo' },
      { name: 'Joselu Mato', clue: 'Clásico' },
      { name: 'Ferran Torres', clue: 'Variable' },
      { name: 'Lamine Yamal', clue: 'Prometedor' },
      { name: 'Alejandro Balde', clue: 'Ágil' },
      { name: 'Unai Simón', clue: 'Seguro' },
      { name: 'Mikel Oyarzabal', clue: 'Constante' },
      { name: 'Nico Williams', clue: 'Explosivo' },
      { name: 'Iñaki Williams', clue: 'Rápido' },
      { name: 'Álex Remiro', clue: 'Calma' },
      { name: 'Dani Olmo', clue: 'Técnico' },
      { name: 'Takefusa Kubo', clue: 'Hábil' },
      { name: 'Alejandro Garnacho', clue: 'Atrevido' },
      { name: 'Enzo Fernández', clue: 'Elegante' },
      { name: 'Julián Álvarez', clue: 'Persistente' },
      { name: 'Alexis Mac Allister', clue: 'Preciso' },
      { name: 'Bukayo Saka', clue: 'Decidido' },
      { name: 'Martin Ødegaard', clue: 'Creativo' },
      { name: 'Jude Bellingham', clue: 'Completo' },
      { name: 'Victor Osimhen', clue: 'Rápido' },
      { name: 'Khvicha Kvaratskhelia', clue: 'Imaginativo' },
      { name: 'Florian Wirtz', clue: 'Promesa' },
    ],
  },
  comida: {
    id: 'comida',
    name: 'Comida',
    players: [], // Se llenará más adelante
  },
  ciudades: {
    id: 'ciudades',
    name: 'Ciudades',
    players: [], // Se llenará más adelante
  },
};

// Función para obtener un jugador aleatorio de una categoría
export const getRandomPlayer = (categoryId: string): PlayerWithClue | null => {
  const category = gameData[categoryId];
  if (!category || category.players.length === 0) return null;
  const randomIndex = Math.floor(Math.random() * category.players.length);
  return category.players[randomIndex];
};


